---
fail_fast: false
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.4.0"
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: mixed-line-ending
        args: [--fix, "lf"]
      - id: no-commit-to-branch
        args: [--branch, main, --branch, master, --branch, devel]
      - id: trailing-whitespace
  - repo: https://github.com/adrienverge/yamllint
    rev: "v1.32.0"
    hooks:
      - id: yamllint
