---
name: Build SST within Spack

# yamllint disable-line rule:truthy
on:
  pull_request:
  push:

jobs:
  install-spack:
    runs-on: ubuntu-latest
    name: Within Spack version ${{ matrix.version }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
        version:
          - '13.1.0'
    steps:
      - uses: actions/checkout@v4
      - name: Install Spack
        uses: vsoch/spack-package-action/install@main
      - name: Install sst-core, sst-elements, and sst-macro
        run: |
          spack env create sst
          spack env activate sst
          spack add sst-core@${{ matrix.version }}
          spack add sst-elements@${{ matrix.version }}
          spack add sst-macro@${{ matrix.version }}
          spack install
