---
name: Build SST within Spack

# yamllint disable-line rule:truthy
on:
  pull_request:
  push:

jobs:
  install-spack:
    runs-on: ${{ matrix.os }}
    name: version:${{ matrix.version }} / os:${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
        version:
          - '13.1.0'
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Clone Spack
        uses: actions/checkout@v4
        with:
          repository: spack/spack
          path: spack
      - name: Add Spack to PATH and set mirror name
        run: |
          echo "${PWD}/spack/bin" >> "${GITHUB_PATH}"
          echo "mirror_name=github-container-registry" >> "${GITHUB_ENV}"
      - name: Print Spack configuration
        run: |
          spack config blame config
      - name: Set credentials for mirror
        run: |
          eval "$(spack env activate --sh .)"
          spack mirror set \
              --oci-username ${{ github.actor }} \
              --oci-password "${{ secrets.GITHUB_TOKEN }}" \
              "${mirror_name}"
      - name: Install sst-core, sst-elements, and sst-macro
        run: |
          eval "$(spack env activate --sh .)"
          # spack add sst-core@${{ matrix.version }}
          # spack add sst-elements@${{ matrix.version }}
          # spack add sst-macro@${{ matrix.version }}
          spack add perl
          spack install --fail-fast
      - name: Push packages and update index
        run: |
          eval "$(spack env activate --sh .)"
          spack -d buildcache push \
              --unsigned \
              --update-index \
              "${mirror_name}"
        if: ${{ !cancelled() }}
