---
name: Build SST within Spack

# yamllint disable-line rule:truthy
on:
  pull_request:
  push:

jobs:
  install-spack:
    runs-on: ubuntu-latest
    name: Within Spack version:${{ matrix.version }} / os:${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
        version:
          - '13.1.0'
    steps:
      - uses: actions/checkout@v4
      - name: Clone Spack
        uses: actions/checkout@v4
        with:
          repository: spack/spack
          path: spack
      - name: Add Spack to PATH
        run: |
          echo "${PWD}/spack/bin" >> "${GITHUB_PATH}"
      - name: Install sst-core, sst-elements, and sst-macro
        run: |
          echo "PATH: ${PATH}"
          echo "GITHUB_PATH: ${GITHUB_PATH}"
          [[ -n "${GITHUB_PATH}" ]] && cat "${GITHUB_PATH}"
          spack env create sst
          spack env activate sst
          spack add sst-core@${{ matrix.version }}
          spack add sst-elements@${{ matrix.version }}
          spack add sst-macro@${{ matrix.version }}
          spack install
