---
# In the absence of using the pre-commit.ci service...
name: pre-commit

# yamllint disable-line rule:truthy
on:
  pull_request:
  push:

jobs:
  pre-commit:
    runs-on: ubuntu-26.04
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false
      - uses: j178/prek-action@v3.0.1
